-- Add timestamps introduced in the Prisma schema after the initial migration.
ALTER TABLE "Rant"
ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Rant"
ALTER COLUMN "updatedAt" DROP DEFAULT;

ALTER TABLE "Like"
ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Like"
ALTER COLUMN "updatedAt" DROP DEFAULT;
